import{a as E,S as $,i as h}from"./assets/vendor-b11e2a50.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const v="44800036-3797b6ab3e55b410f8e06bcc9",M="https://pixabay.com/api/";async function g(t,o=1,i=15){const n=`${M}?key=${v}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=${i}`;try{return(await E.get(n)).data}catch(e){throw console.error("Error fetching images:",e),e}}let u;function B(){const t=document.querySelector(".gallery");t.innerHTML=""}function y(t){const o=document.querySelector(".gallery"),i=t.map(({webformatURL:n,largeImageURL:e,tags:r,likes:a,views:L,comments:S,downloads:q})=>`
      <a class="gallery-item" href="${e}">
        <img src="${n}" alt="${r}" loading="lazy" width="360px" height="252px"/>
        <div class="info info-wrap">
          <p class="info-item info-item-css"><b>Likes:</b> ${a}</p>
          <p class="info-item info-item-css"><b>Views:</b> ${L}</p>
          <p class="info-item info-item-css"><b>Comments:</b> ${S}</p>
          <p class="info-item info-item-css"><b>Downloads:</b> ${q}</p>
        </div>
      </a>
    `).join("");o.insertAdjacentHTML("beforeend",i),u?u.refresh():u=new $(".gallery a")}function P(){h.info({title:"Sorry",message:"There are no images matching your search query. Please try again!"})}function p(){document.querySelector(".loader").classList.remove("hidden")}function b(){document.querySelector(".loader").classList.add("hidden")}function I(){document.querySelector("#load-more").classList.remove("hidden")}function f(){document.querySelector("#load-more").classList.add("hidden")}function m(){h.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."})}let l="",s=1,d=0;const c=15,w=document.querySelector("#search-form"),O=w.querySelector("input"),x=document.querySelector("#load-more");w.addEventListener("submit",async t=>{if(t.preventDefault(),l=O.value.trim(),!!l){B(),f(),p(),s=1;try{const o=await g(l,s,c);d=o.totalHits,o.hits.length===0?P():(y(o.hits),s*c<d&&I())}catch(o){console.error("Error:",o),iziToast.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{b()}}});x.addEventListener("click",async()=>{p(),s+=1;try{const t=await g(l,s,c);t.hits.length===0||s*c>=d?(m(),f()):(y(t.hits),window.scrollBy({top:document.querySelector(".gallery").firstElementChild.getBoundingClientRect().height*2,behavior:"smooth"}),s*c>=d&&(m(),f()))}catch(t){console.error("Error:",t),iziToast.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{b()}});
//# sourceMappingURL=commonHelpers.js.map
