import{a as q,S as E,i as f}from"./assets/vendor-b11e2a50.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const $="44800036-3797b6ab3e55b410f8e06bcc9",v="https://pixabay.com/api/";async function m(t,o=1,i=15){const s=`${v}?key=${$}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=${i}`;try{return(await q.get(s)).data}catch(e){throw console.error("Error fetching images:",e),e}}let d;function M(){const t=document.querySelector(".gallery");t.innerHTML=""}function h(t){const o=document.querySelector(".gallery"),i=t.map(({webformatURL:s,largeImageURL:e,tags:r,likes:a,views:w,comments:L,downloads:S})=>`
      <a class="gallery-item" href="${e}">
        <img src="${s}" alt="${r}" loading="lazy" width="360px" height="252px"/>
        <div class="info info-wrap">
          <p class="info-item info-item-css"><b>Likes:</b> ${a}</p>
          <p class="info-item info-item-css"><b>Views:</b> ${w}</p>
          <p class="info-item info-item-css"><b>Comments:</b> ${L}</p>
          <p class="info-item info-item-css"><b>Downloads:</b> ${S}</p>
        </div>
      </a>
    `).join("");o.insertAdjacentHTML("beforeend",i),d?d.refresh():d=new E(".gallery a")}function B(){f.info({title:"Sorry",message:"There are no images matching your search query. Please try again!"})}function g(){document.querySelector(".loader").classList.remove("hidden")}function y(){document.querySelector(".loader").classList.add("hidden")}function P(){document.querySelector("#load-more").classList.remove("hidden")}function p(){document.querySelector("#load-more").classList.add("hidden")}function I(){f.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."})}let c="",n=1,u=0;const l=15,b=document.querySelector("#search-form"),O=b.querySelector("input"),x=document.querySelector("#load-more");b.addEventListener("submit",async t=>{if(t.preventDefault(),c=O.value.trim(),!!c){M(),p(),g(),n=1;try{const o=await m(c,n,l);u=o.totalHits,o.hits.length===0?B():(h(o.hits),n*l<u&&P())}catch(o){console.error("Error:",o),iziToast.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{y()}}});x.addEventListener("click",async()=>{g(),n+=1;try{const t=await m(c,n,l);h(t.hits),n*l>=u?(I(),p()):window.scrollBy({top:document.querySelector(".gallery").firstElementChild.getBoundingClientRect().height*2,behavior:"smooth"})}catch(t){console.error("Error:",t),iziToast.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{y()}});
//# sourceMappingURL=commonHelpers.js.map
