import{a as S,S as q,i as u}from"./assets/vendor-b11e2a50.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const E="44800036-3797b6ab3e55b410f8e06bcc9",$="https://pixabay.com/api/";async function f(t,o=1,n=15){const s=`${$}?key=${E}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=${n}`;try{return(await S.get(s)).data}catch(e){throw console.error("Error fetching images:",e),e}}let c;function v(){const t=document.querySelector(".gallery");t.innerHTML=""}function m(t){const o=document.querySelector(".gallery"),n=t.map(({webformatURL:s,largeImageURL:e,tags:r,likes:i,views:b,comments:w,downloads:L})=>`
      <a class="gallery-item" href="${e}">
        <img src="${s}" alt="${r}" loading="lazy" width="360px" height="252px"/>
        <div class="info info-wrap">
          <p class="info-item info-item-css"><b>Likes:</b> ${i}</p>
          <p class="info-item info-item-css"><b>Views:</b> ${b}</p>
          <p class="info-item info-item-css"><b>Comments:</b> ${w}</p>
          <p class="info-item info-item-css"><b>Downloads:</b> ${L}</p>
        </div>
      </a>
    `).join("");o.insertAdjacentHTML("beforeend",n),c?c.refresh():c=new q(".gallery a")}function M(){u.info({title:"Sorry",message:"There are no images matching your search query. Please try again!"})}function h(){document.querySelector(".loader").classList.remove("hidden")}function g(){document.querySelector(".loader").classList.add("hidden")}function B(){document.querySelector("#load-more").classList.remove("hidden")}function y(){document.querySelector("#load-more").classList.add("hidden")}function P(){u.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."})}let l="",a=1,d=0;const p=document.querySelector("#search-form"),I=p.querySelector("input"),O=document.querySelector("#load-more");p.addEventListener("submit",async t=>{if(t.preventDefault(),l=I.value.trim(),!!l){v(),y(),h(),a=1;try{const o=await f(l,a);d=o.totalHits,o.hits.length===0?M():(m(o.hits),o.hits.length<d&&B())}catch(o){console.error("Error:",o),iziToast.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{g()}}});O.addEventListener("click",async()=>{h(),a+=1;try{const t=await f(l,a);t.hits.length===0||a*15>=d?(P(),y()):(m(t.hits),window.scrollBy({top:document.querySelector(".gallery").firstElementChild.getBoundingClientRect().height*2,behavior:"smooth"}))}catch(t){console.error("Error:",t),iziToast.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{g()}});
//# sourceMappingURL=commonHelpers.js.map
